"""add created by to inventory transactions

Revision ID: 2075675a97b4
Revises: 102247c2494c
Create Date: 2026-09-20 14:00:56.830238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2075675a97b4'
down_revision: Union[str, Sequence[str], None] = '102247c2494c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'reference',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_transactions_created_by'), 'inventory_transactions', ['created_by'], unique=False)
    op.create_foreign_key(None, 'inventory_transactions', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_transactions_created_by'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'reference',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('inventory_transactions', 'created_by')
    # ### end Alembic commands ###
